name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0
      - name: Test
        run: bin/test.sh
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@0.2.0
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: 'tests/**/coverage.cobertura.xml'
